### ISSUE TITLE
Cannot find module '@babel/core'

### ISSUE THREAD

**Issue by tiholic** [kenchan0130/babel-preset-google-apps-script#30]
Running "babel:extensions" (babel) task
Warning: Cannot find module '@babel/core' (While processing preset: "/Users/rohit/dpapp/documerge.io/static_server/node_modules/@kenchan0130/babel-preset-google-apps-script/dist/index.js") Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 3

**Comment by kenchan0130** [comment]
@tiholic 
Thank you for your report.
This library does not depend on `@babel/core`, only devDependencies.

Can you check if the `@babel/core` version is up to date?
[My sample project](https://github.com/kenchan0130/2ch-rss-gas) has been successfully built.

**Comment by tiholic** [comment]
Okay, I'm using babel < 7. Could be related to that.

Anyways, the problem I had was to polyfill Symbol which was not known to apps script. So I added a Symbol polyfill script to gs code, with some mods.
